### ISSUE TITLE
Circular argument reference in ltap with ruby 2.7.1

### ISSUE THREAD

**Issue by thisismiller** [brandur/hutils#18]
```
$ rbenv versions
  system
* 2.7.1 (set by /home/thisismiller/.rbenv/version)
```

```
$ ltap --help
Traceback (most recent call last):
	5: from /home/thisismiller/.rbenv/versions/2.7.1/bin/ltap:23:in `<main>'
	4: from /home/thisismiller/.rbenv/versions/2.7.1/bin/ltap:23:in `load'
	3: from /home/thisismiller/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hutils-0.3.3/bin/ltap:6:in `<top (required)>'
	2: from /home/thisismiller/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hutils-0.3.3/bin/ltap:6:in `require_relative'
	1: from /home/thisismiller/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hutils-0.3.3/lib/hutils/ltap.rb:5:in `<top (required)>'
/home/thisismiller/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hutils-0.3.3/lib/hutils/ltap.rb:5:in `require_relative': /home/thisismiller/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hutils-0.3.3/lib/hutils/ltap/time_bound_parser.rb:19: circular argument reference - from (SyntaxError)
```

The line in question appears to be

```
    def to_date(num, unit, from: from)
```

So the repeated `from` appears to be the complaint, but I have no idea how ruby works to give you a fix.

**Comment by brandur** [comment]
Thanks for the report!

Dang it though — sorry to report this, but this project hasn't been maintained for years :/

Have you seen angle-grinder? I think you're about a million times more likely to get what you want with that:

https://github.com/rcoh/angle-grinder
